version: '3'
services:
  stepper_motor_service:
    build: ./src/motor-controller
    container_name: stepper_motor_service
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    environment:
      - STEP_PIN=17
      - DIR_PIN=27
      - ENABLE_PIN=22
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped